apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: guard-kube
  annotations:
    guard.io/security-components: "[\"firewall\"]"
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      # container - lcp
      # - name: lcp
      #   image: guardproject/lcp:latest
      #   env:
      #   - name: LCP_GIT_URL
      #     value: "https://guard-token:2nsubUuUss8sQ-Mue_yN@gitlab.com/guard-repositories/lcp"
      #   - name: LCP_ROOT
      #     value: "/root/lcp"
      #   - name: HOST
      #     value: "0.0.0.0"
      #   - name: PORT
      #     value: "4000"
      #   - name: DEV_USERNAME
      #     value: "lcp"
      #   - name: DEV_PASSWORD
      #     value: "a9d4034da07d8ef31db1cd4119b6a4552fdfbd19787e2848e71c8ee3b47703a7" # "guard" in hashed sha256
      #   - name: LOG_LEVEL
      #     value: "DEBUG"
      #   - name: FORCE_APT_UPGRADE_BOOT
      #     value: "no"
      #   - name: FORCE_REBUILD_BOOT
      #     value: "no"
      #   - name: USE_ENV_CONFIG_FILES
      #     value: "yes"
      #   ports:
      #   - containerPort: 4000
      #   volumeMounts:
      #   - name: mysql-metricbeat-config
      #     mountPath: /root/metricbeat/config/
      #   - name: mysql-metricbeat-modules
      #     mountPath: /root/metricbeat/modules.d/
      #   - name: mysql-logstash
      #     mountPath: /root/logstash/config/
      #   - name: mysql-logstash-conf
      #     mountPath: /root/logstash/pipeline/
      # /container - lcp

      # container - mysql
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - containerPort: 3601
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/my.cnf.new
          subPath: my.cnf.new
        - name: proc
          mountPath: /proc
        - name: cgroup
          mountPath: /sys/fs/cgroup
      # /container  - mysql

      # container - polycube
      - name: polycubed
        image: polycubenetwork/polycube:latest
        command: ["polycubed", "--loglevel=DEBUG", "--addr=0.0.0.0", "--logfile=/host/var/log/pcn_k8s"]
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-src
          mountPath: /usr/src
        - name: cni-path
          mountPath: /host/opt/cni/bin
        - name: etc-cni-netd
          mountPath: /host/etc/cni/net.d
        - name: var-log
          mountPath: /host/var/log
        securityContext:
          privileged: true
        ports:
          - name: polycubed
            containerPort: 9000
        terminationMessagePolicy: FallbackToLogsOnError
      # /container  - polycube

      # container - metricbeat
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:7.2.0
        args: ["-c", "/usr/share/metricbeat/config/metricbeat.yml"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: mysql-metricbeat-config
          mountPath: /usr/share/metricbeat/config/
        - name: mysql-metricbeat-modules
          mountPath: /usr/share/metricbeat/modules.d/
        - name: proc
          mountPath: /proc
        - name: cgroup
          mountPath: /sys/fs/cgroup
      # /container - metricbeat

      # container - logstash
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.2.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 5144
        volumeMounts:
          - name: mysql-logstash
            mountPath: /usr/share/logstash/config/
          - name: mysql-logstash-conf
            mountPath: /usr/share/logstash/pipeline/
      # /container - logstash

      volumes:
      # volumes - mysql
      - name: mysql-conf
        configMap:
          name: mysql-conf
          items:
          - key: my.cnf
            path: my.cnf
      # /volumes - mysql

      # volumes - mysql + polycube + metricbeat
      - name: proc
        hostPath:
          path: /proc
      # /volumes - mysql + polycube + metricbeat

      # volumes - mysql + metricbeat
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      # /volumes - mysql + metricbeat

      # volumes - polycube
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: cni-path
        hostPath:
          path: /opt/cni/bin
      - name: etc-cni-netd
        hostPath:
          path: /etc/cni/net.d
      - name: var-log
        hostPath:
          path: /var/log
      - name: netns
        hostPath:
          path: /var/run/netns
        # /volumes - polycube

      # volumes- metricbeat
      - name: mysql-metricbeat-config
        configMap:
          name: mysql-metricbeat
          items:
          - key: metricbeat.yml
            path: metricbeat.yml
      - name: mysql-metricbeat-modules
        configMap:
          name: mysql-metricbeat
          items:
          - key: mysql.yml
            path: mysql.yml
          - key: system.yml
            path: system.yml
      # /volumes - metricbeat

      # volumes - logstash
      - name: mysql-logstash
        configMap:
          name: mysql-logstash
          items:
          - key: logstash.yml
            path: logstash.yml
          - key: pipelines.yml
            path: pipelines.yml
          - key: log4j2.properties
            path: log4j2.properties
      - name: mysql-logstash-conf
        configMap:
          name: mysql-logstash
          items:
          - key: mysql-system.conf
            path: mysql-system.conf
      # /volumes - logstash
