apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: guard-kube
  annotations:
    guard.io/security-components: "[\"firewall\"]"
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      # container - mysql
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - containerPort: 3601
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/my.cnf.new
          subPath: my.cnf.new
        - name: proc
          mountPath: /proc
        - name: cgroup
          mountPath: /sys/fs/cgroup
      # /container  - mysql

      # container - metricbeat
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:7.2.0
        args: ["-c", "/usr/share/metricbeat/config/metricbeat.yml"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: mysql-metricbeat-config
          mountPath: /usr/share/metricbeat/config/
        - name: mysql-metricbeat-modules
          mountPath: /usr/share/metricbeat/modules.d/
        - name: proc
          mountPath: /proc
        - name: cgroup
          mountPath: /sys/fs/cgroup
      # /container - metricbeat

      # container - logstash
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.2.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 5144
        volumeMounts:
          - name: mysql-logstash
            mountPath: /usr/share/logstash/config/
          - name: mysql-logstash-conf
            mountPath: /usr/share/logstash/pipeline/
      # /container - logstash

      initContainers:
      - name: copy
        image: busybox
        command: ["sh", "-c"]
        args:
        - "cp /mysql-metricbeat-modules-data/* /mysql-metricbeat-modules/"
        volumeMounts:
        - name: mysql-metricbeat-modules
          mountPath: /mysql-metricbeat-modules
        - name: mysql-metricbeat-modules-data
          mountPath: /mysql-metricbeat-modules-data

      volumes:
      # volumes - mysql
      - name: mysql-conf
        configMap:
          name: mysql-conf
          items:
          - key: my.cnf
            path: my.cnf
      # /volumes - mysql

      # volumes - mysql + metricbeat
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      # /volumes - mysql + metricbeat

      # volumes- metricbeat
      - name: mysql-metricbeat-config
        configMap:
          name: mysql-metricbeat
          items:
          - key: metricbeat.yml
            path: metricbeat.yml
      - name: mysql-metricbeat-modules
        emptyDir: {}
      - name: mysql-metricbeat-modules-data
        configMap:
          name: mysql-metricbeat
          items:
          - key: mysql.yml
            path: mysql.yml
          - key: system.yml
            path: system.yml
      # /volumes - metricbeat

      # volumes - logstash
      - name: mysql-logstash
        configMap:
          name: mysql-logstash
          items:
          - key: logstash.yml
            path: logstash.yml
          - key: pipelines.yml
            path: pipelines.yml
          - key: log4j2.properties
            path: log4j2.properties
      - name: mysql-logstash-conf
        configMap:
          name: mysql-logstash
          items:
          - key: mysql-system.conf
            path: mysql-system.conf
      # /volumes - logstash
