apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: guard-kube
  labels:
    app: context-broker
spec:
  selector:
    app: context-broker
  type: LoadBalancer
  ports:
  - name: elasticsearch-port
    port: 9200
