apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: guard-kube
  labels:
    app: context-broker
spec:
  selector:
    app: context-broker
  type: LoadBalancer
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
