apiVersion: v1
kind: Service
metadata:
  name: kafka-bus
  namespace: guard-kube
  labels:
    app: context-broker
spec:
  selector:
    app: context-broker
  type: NodePort
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    nodePort: 30992