apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kibana-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi